os:
  - linux
  - osx

language: go

go:
    - 1.9.x

install: true

before_install:
  - make deps

script:
  - go vet ./...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go test -v -race -coverprofile=coverage.txt -covermode=atomic .;
    else go test -v -race .; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
